import React from 'react';
import Clock from './Clock';


const App = () =>
{
    return ([
        <h1>Timezones</h1>,
        <section className="container">
            {Clock("Africa/Abidjan")}
            {Clock("Africa/Accra")}
            {Clock("Africa/Addis_Ababa")}
            {Clock("Africa/Algiers")}
            {Clock("Africa/Asmara")}
            {Clock("Africa/Bamako")}
            {Clock("Africa/Bangui")}
            {Clock("Africa/Banjul")}
            {Clock("Africa/Bissau")}
            {Clock("Africa/Blantyre")}
            {Clock("Africa/Brazzaville")}
            {Clock("Africa/Bujumbura")}
            {Clock("Africa/Cairo")}
            {Clock("Africa/Casablanca")}
            {Clock("Africa/Ceuta")}
            {Clock("Africa/Conakry")}
            {Clock("Africa/Dakar")}
            {Clock("Africa/Dar_es_Salaam")}
            {Clock("Africa/Djibouti")}
            {Clock("Africa/Douala")}
            {Clock("Africa/El_Aaiun")}
            {Clock("Africa/Freetown")}
            {Clock("Africa/Gaborone")}
            {Clock("Africa/Harare")}
            {Clock("Africa/Johannesburg")}
            {Clock("Africa/Juba")}
            {Clock("Africa/Kampala")}
            {Clock("Africa/Khartoum")}
            {Clock("Africa/Kigali")}
            {Clock("Africa/Kinshasa")}
            {Clock("Africa/Lagos")}
            {Clock("Africa/Libreville")}
            {Clock("Africa/Lome")}
            {Clock("Africa/Luanda")}
            {Clock("Africa/Lubumbashi")}
            {Clock("Africa/Lusaka")}
            {Clock("Africa/Malabo")}
            {Clock("Africa/Maputo")}
            {Clock("Africa/Maseru")}
            {Clock("Africa/Mbabane")}
            {Clock("Africa/Mogadishu")}
            {Clock("Africa/Monrovia")}
            {Clock("Africa/Nairobi")}
            {Clock("Africa/Ndjamena")}
            {Clock("Africa/Niamey")}
            {Clock("Africa/Nouakchott")}
            {Clock("Africa/Ouagadougou")}
            {Clock("Africa/Porto-Novo")}
            {Clock("Africa/Sao_Tome")}
            {Clock("Africa/Tripoli")}
            {Clock("Africa/Tunis")}
            {Clock("Africa/Windhoek")}
            {Clock("America/Adak")}
            {Clock("America/Anchorage")}
            {Clock("America/Anguilla")}
            {Clock("America/Antigua")}
            {Clock("America/Araguaina")}
            {Clock("America/Argentina/Buenos_Aires")}
            {Clock("America/Argentina/Catamarca")}
            {Clock("America/Argentina/Cordoba")}
            {Clock("America/Argentina/Jujuy")}
            {Clock("America/Argentina/La_Rioja")}
            {Clock("America/Argentina/Mendoza")}
            {Clock("America/Argentina/Rio_Gallegos")}
            {Clock("America/Argentina/Salta")}
            {Clock("America/Argentina/San_Juan")}
            {Clock("America/Argentina/San_Luis")}
            {Clock("America/Argentina/Tucuman")}
            {Clock("America/Argentina/Ushuaia")}
            {Clock("America/Aruba")}
            {Clock("America/Asuncion")}
            {Clock("America/Atikokan")}
            {Clock("America/Bahia")}
            {Clock("America/Bahia_Banderas")}
            {Clock("America/Barbados")}
            {Clock("America/Belem")}
            {Clock("America/Belize")}
            {Clock("America/Blanc-Sablon")}
            {Clock("America/Boa_Vista")}
            {Clock("America/Bogota")}
            {Clock("America/Boise")}
            {Clock("America/Cambridge_Bay")}
            {Clock("America/Campo_Grande")}
            {Clock("America/Cancun")}
            {Clock("America/Caracas")}
            {Clock("America/Cayenne")}
            {Clock("America/Cayman")}
            {Clock("America/Chicago")}
            {Clock("America/Chihuahua")}
            {Clock("America/Costa_Rica")}
            {Clock("America/Creston")}
            {Clock("America/Cuiaba")}
            {Clock("America/Curacao")}
            {Clock("America/Danmarkshavn")}
            {Clock("America/Dawson")}
            {Clock("America/Dawson_Creek")}
            {Clock("America/Denver")}
            {Clock("America/Detroit")}
            {Clock("America/Dominica")}
            {Clock("America/Edmonton")}
            {Clock("America/Eirunepe")}
            {Clock("America/El_Salvador")}
            {Clock("America/Fort_Nelson")}
            {Clock("America/Fortaleza")}
            {Clock("America/Glace_Bay")}
            {Clock("America/Godthab")}
            {Clock("America/Goose_Bay")}
            {Clock("America/Grand_Turk")}
            {Clock("America/Grenada")}
            {Clock("America/Guadeloupe")}
            {Clock("America/Guatemala")}
            {Clock("America/Guayaquil")}
            {Clock("America/Guyana")}
            {Clock("America/Halifax")}
            {Clock("America/Havana")}
            {Clock("America/Hermosillo")}
            {Clock("America/Indiana/Indianapolis")}
            {Clock("America/Indiana/Knox")}
            {Clock("America/Indiana/Marengo")}
            {Clock("America/Indiana/Petersburg")}
            {Clock("America/Indiana/Tell_City")}
            {Clock("America/Indiana/Vevay")}
            {Clock("America/Indiana/Vincennes")}
            {Clock("America/Indiana/Winamac")}
            {Clock("America/Inuvik")}
            {Clock("America/Iqaluit")}
            {Clock("America/Jamaica")}
            {Clock("America/Juneau")}
            {Clock("America/Kentucky/Louisville")}
            {Clock("America/Kentucky/Monticello")}
            {Clock("America/Kralendijk")}
            {Clock("America/La_Paz")}
            {Clock("America/Lima")}
            {Clock("America/Los_Angeles")}
            {Clock("America/Lower_Princes")}
            {Clock("America/Maceio")}
            {Clock("America/Managua")}
            {Clock("America/Manaus")}
            {Clock("America/Marigot")}
            {Clock("America/Martinique")}
            {Clock("America/Matamoros")}
            {Clock("America/Mazatlan")}
            {Clock("America/Menominee")}
            {Clock("America/Merida")}
            {Clock("America/Metlakatla")}
            {Clock("America/Mexico_City")}
            {Clock("America/Miquelon")}
            {Clock("America/Moncton")}
            {Clock("America/Monterrey")}
            {Clock("America/Montevideo")}
            {Clock("America/Montserrat")}
            {Clock("America/Nassau")}
            {Clock("America/New_York")}
            {Clock("America/Nipigon")}
            {Clock("America/Nome")}
            {Clock("America/Noronha")}
            {Clock("America/North_Dakota/Beulah")}
            {Clock("America/North_Dakota/Center")}
            {Clock("America/North_Dakota/New_Salem")}
            {Clock("America/Ojinaga")}
            {Clock("America/Panama")}
            {Clock("America/Pangnirtung")}
            {Clock("America/Paramaribo")}
            {Clock("America/Phoenix")}
            {Clock("America/Port-au-Prince")}
            {Clock("America/Port_of_Spain")}
            {Clock("America/Porto_Velho")}
            {Clock("America/Puerto_Rico")}
            {Clock("America/Rainy_River")}
            {Clock("America/Rankin_Inlet")}
            {Clock("America/Recife")}
            {Clock("America/Regina")}
            {Clock("America/Resolute")}
            {Clock("America/Rio_Branco")}
            {Clock("America/Santarem")}
            {Clock("America/Santiago")}
            {Clock("America/Santo_Domingo")}
            {Clock("America/Sao_Paulo")}
            {Clock("America/Scoresbysund")}
            {Clock("America/Sitka")}
            {Clock("America/St_Barthelemy")}
            {Clock("America/St_Johns")}
            {Clock("America/St_Kitts")}
            {Clock("America/St_Lucia")}
            {Clock("America/St_Thomas")}
            {Clock("America/St_Vincent")}
            {Clock("America/Swift_Current")}
            {Clock("America/Tegucigalpa")}
            {Clock("America/Thule")}
            {Clock("America/Thunder_Bay")}
            {Clock("America/Tijuana")}
            {Clock("America/Toronto")}
            {Clock("America/Tortola")}
            {Clock("America/Vancouver")}
            {Clock("America/Whitehorse")}
            {Clock("America/Winnipeg")}
            {Clock("America/Yakutat")}
            {Clock("America/Yellowknife")}
            {Clock("Antarctica/Casey")}
            {Clock("Antarctica/Davis")}
            {Clock("Antarctica/DumontDUrville")}
            {Clock("Antarctica/Macquarie")}
            {Clock("Antarctica/Mawson")}
            {Clock("Antarctica/Palmer")}
            {Clock("Antarctica/Rothera")}
            {Clock("Antarctica/Syowa")}
            {Clock("Antarctica/Troll")}
            {Clock("Antarctica/Vostok")}
            {Clock("Arctic/Longyearbyen")}
            {Clock("Asia/Aden")}
            {Clock("Asia/Almaty")}
            {Clock("Asia/Amman")}
            {Clock("Asia/Anadyr")}
            {Clock("Asia/Aqtau")}
            {Clock("Asia/Aqtobe")}
            {Clock("Asia/Ashgabat")}
            {Clock("Asia/Baghdad")}
            {Clock("Asia/Bahrain")}
            {Clock("Asia/Baku")}
            {Clock("Asia/Bangkok")}
            {Clock("Asia/Barnaul")}
            {Clock("Asia/Beirut")}
            {Clock("Asia/Bishkek")}
            {Clock("Asia/Brunei")}
            {Clock("Asia/Chita")}
            {Clock("Asia/Choibalsan")}
            {Clock("Asia/Colombo")}
            {Clock("Asia/Damascus")}
            {Clock("Asia/Dhaka")}
            {Clock("Asia/Dili")}
            {Clock("Asia/Dubai")}
            {Clock("Asia/Dushanbe")}
            {Clock("Asia/Gaza")}
            {Clock("Asia/Hebron")}
            {Clock("Asia/Ho_Chi_Minh")}
            {Clock("Asia/Hong_Kong")}
            {Clock("Asia/Hovd")}
            {Clock("Asia/Irkutsk")}
            {Clock("Asia/Jakarta")}
            {Clock("Asia/Jayapura")}
            {Clock("Asia/Jerusalem")}
            {Clock("Asia/Kabul")}
            {Clock("Asia/Kamchatka")}
            {Clock("Asia/Karachi")}
            {Clock("Asia/Kathmandu")}
            {Clock("Asia/Khandyga")}
            {Clock("Asia/Kolkata")}
            {Clock("Asia/Krasnoyarsk")}
            {Clock("Asia/Kuala_Lumpur")}
            {Clock("Asia/Kuching")}
            {Clock("Asia/Kuwait")}
            {Clock("Asia/Macau")}
            {Clock("Asia/Magadan")}
            {Clock("Asia/Makassar")}
            {Clock("Asia/Manila")}
            {Clock("Asia/Muscat")}
            {Clock("Asia/Nicosia")}
            {Clock("Asia/Novokuznetsk")}
            {Clock("Asia/Novosibirsk")}
            {Clock("Asia/Omsk")}
            {Clock("Asia/Oral")}
            {Clock("Asia/Phnom_Penh")}
            {Clock("Asia/Pontianak")}
            {Clock("Asia/Pyongyang")}
            {Clock("Asia/Qatar")}
            {Clock("Asia/Qyzylorda")}
            {Clock("Asia/Riyadh")}
            {Clock("Asia/Sakhalin")}
            {Clock("Asia/Samarkand")}
            {Clock("Asia/Seoul")}
            {Clock("Asia/Shanghai")}
            {Clock("Asia/Singapore")}
            {Clock("Asia/Srednekolymsk")}
            {Clock("Asia/Taipei")}
            {Clock("Asia/Tashkent")}
            {Clock("Asia/Tbilisi")}
            {Clock("Asia/Tehran")}
            {Clock("Asia/Thimphu")}
            {Clock("Asia/Tokyo")}
            {Clock("Asia/Tomsk")}
            {Clock("Asia/Ulaanbaatar")}
            {Clock("Asia/Urumqi")}
            {Clock("Asia/Ust-Nera")}
            {Clock("Asia/Vientiane")}
            {Clock("Asia/Vladivostok")}
            {Clock("Asia/Yakutsk")}
            {Clock("Asia/Yangon")}
            {Clock("Asia/Yekaterinburg")}
            {Clock("Asia/Yerevan")}
            {Clock("Atlantic/Azores")}
            {Clock("Atlantic/Bermuda")}
            {Clock("Atlantic/Canary")}
            {Clock("Atlantic/Cape_Verde")}
            {Clock("Atlantic/Faroe")}
            {Clock("Atlantic/Madeira")}
            {Clock("Atlantic/Reykjavik")}
            {Clock("Atlantic/South_Georgia")}
            {Clock("Atlantic/St_Helena")}
            {Clock("Atlantic/Stanley")}
            {Clock("Australia/Adelaide")}
            {Clock("Australia/Brisbane")}
            {Clock("Australia/Broken_Hill")}
            {Clock("Australia/Currie")}
            {Clock("Australia/Darwin")}
            {Clock("Australia/Eucla")}
            {Clock("Australia/Hobart")}
            {Clock("Australia/Lindeman")}
            {Clock("Australia/Lord_Howe")}
            {Clock("Australia/Melbourne")}
            {Clock("Australia/Perth")}
            {Clock("Australia/Sydney")}
            {Clock("Europe/Amsterdam")}
            {Clock("Europe/Andorra")}
            {Clock("Europe/Astrakhan")}
            {Clock("Europe/Athens")}
            {Clock("Europe/Belgrade")}
            {Clock("Europe/Berlin")}
            {Clock("Europe/Bratislava")}
            {Clock("Europe/Brussels")}
            {Clock("Europe/Bucharest")}
            {Clock("Europe/Budapest")}
            {Clock("Europe/Busingen")}
            {Clock("Europe/Chisinau")}
            {Clock("Europe/Copenhagen")}
            {Clock("Europe/Dublin")}
            {Clock("Europe/Gibraltar")}
            {Clock("Europe/Guernsey")}
            {Clock("Europe/Helsinki")}
            {Clock("Europe/Isle_of_Man")}
            {Clock("Europe/Istanbul")}
            {Clock("Europe/Jersey")}
            {Clock("Europe/Kaliningrad")}
            {Clock("Europe/Kiev")}
            {Clock("Europe/Kirov")}
            {Clock("Europe/Lisbon")}
            {Clock("Europe/Ljubljana")}
            {Clock("Europe/London")}
            {Clock("Europe/Luxembourg")}
            {Clock("Europe/Madrid")}
            {Clock("Europe/Malta")}
            {Clock("Europe/Mariehamn")}
            {Clock("Europe/Minsk")}
            {Clock("Europe/Monaco")}
            {Clock("Europe/Moscow")}
            {Clock("Europe/Oslo")}
            {Clock("Europe/Paris")}
            {Clock("Europe/Podgorica")}
            {Clock("Europe/Prague")}
            {Clock("Europe/Riga")}
            {Clock("Europe/Rome")}
            {Clock("Europe/Samara")}
            {Clock("Europe/San_Marino")}
            {Clock("Europe/Sarajevo")}
            {Clock("Europe/Simferopol")}
            {Clock("Europe/Skopje")}
            {Clock("Europe/Sofia")}
            {Clock("Europe/Stockholm")}
            {Clock("Europe/Tallinn")}
            {Clock("Europe/Tirane")}
            {Clock("Europe/Ulyanovsk")}
            {Clock("Europe/Uzhgorod")}
            {Clock("Europe/Vaduz")}
            {Clock("Europe/Vatican")}
            {Clock("Europe/Vienna")}
            {Clock("Europe/Vilnius")}
            {Clock("Europe/Volgograd")}
            {Clock("Europe/Warsaw")}
            {Clock("Europe/Zagreb")}
            {Clock("Europe/Zaporozhye")}
            {Clock("Europe/Zurich")}
            {Clock("Indian/Antananarivo")}
            {Clock("Indian/Chagos")}
            {Clock("Indian/Christmas")}
            {Clock("Indian/Cocos")}
            {Clock("Indian/Comoro")}
            {Clock("Indian/Kerguelen")}
            {Clock("Indian/Mahe")}
            {Clock("Indian/Maldives")}
            {Clock("Indian/Mauritius")}
            {Clock("Indian/Mayotte")}
            {Clock("Indian/Reunion")}
            {Clock("Pacific/Apia")}
            {Clock("Pacific/Auckland")}
            {Clock("Pacific/Bougainville")}
            {Clock("Pacific/Chatham")}
            {Clock("Pacific/Chuuk")}
            {Clock("Pacific/Easter")}
            {Clock("Pacific/Efate")}
            {Clock("Pacific/Enderbury")}
            {Clock("Pacific/Fakaofo")}
            {Clock("Pacific/Fiji")}
            {Clock("Pacific/Funafuti")}
            {Clock("Pacific/Galapagos")}
            {Clock("Pacific/Gambier")}
            {Clock("Pacific/Guadalcanal")}
            {Clock("Pacific/Guam")}
            {Clock("Pacific/Honolulu")}
            {Clock("Pacific/Johnston")}
            {Clock("Pacific/Kiritimati")}
            {Clock("Pacific/Kosrae")}
            {Clock("Pacific/Kwajalein")}
            {Clock("Pacific/Majuro")}
            {Clock("Pacific/Marquesas")}
            {Clock("Pacific/Midway")}
            {Clock("Pacific/Nauru")}
            {Clock("Pacific/Niue")}
            {Clock("Pacific/Norfolk")}
            {Clock("Pacific/Noumea")}
            {Clock("Pacific/Pago_Pago")}
            {Clock("Pacific/Palau")}
            {Clock("Pacific/Pitcairn")}
            {Clock("Pacific/Pohnpei")}
            {Clock("Pacific/Port_Moresby")}
            {Clock("Pacific/Rarotonga")}
            {Clock("Pacific/Saipan")}
            {Clock("Pacific/Tahiti")}
            {Clock("Pacific/Tarawa")}
            {Clock("Pacific/Tongatapu")}
            {Clock("Pacific/Wake")}
            {Clock("Pacific/Wallis")}
        </section>
    ])
};


export default App
